version: '3.4'

services:
  eshopwcfservice:
    image: eshop/wcfservice
    build:
      context: ./src/eShopWCFService
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: mcr.microsoft.com/mssql/server:2022-latest