FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["eShopModernizedWebForms.csproj", "./"]
RUN dotnet restore "eShopModernizedWebForms.csproj"
COPY . .
RUN dotnet build "eShopModernizedWebForms.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eShopModernizedWebForms.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "eShopModernizedWebForms.dll"]
