version: '3.4'

services:
  eshop.modernized.webforms:
    image: eshop/modernizedwebforms
    build:
      context: ./src/eShopModernizedWebForms
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: mcr.microsoft.com/mssql/server:2022-latest
